- include: >
    env-version.yml anyenv_env_name=pyenv anyenv_env_version={{ pyenv.version }} anyenv_env_language=python

- name: install pip libraries
  pip: name={{ item }} state=present executable="{{ anyenv.install_dir }}/envs/pyenv/shims/pip"
  register: anyenv_pip_installed
  with_items: "{{ pyenv.global_packages }}"

- name: rehash pyenv
  shell: >
    "{{ anyenv.install_dir | replace('~', '$HOME') }}/envs/pyenv/bin/pyenv" rehash
  when: anyenv_pip_installed is changed
