- include: >
    env-version.yml anyenv_env_name=rbenv anyenv_env_version={{ rbenv.version }} anyenv_env_language=ruby

# NOTE: We must set user_install=no to install gems to the directory under rbenv.
- name: install gem libraries
  gem:
    name: "{{ item }}"
    user_install: no
    executable: "{{ anyenv.install_dir }}/envs/rbenv/shims/gem"
  register: anyenv_gem_installed
  with_items: "{{ rbenv.global_packages }}"

- name: rehash rbenv
  shell: >
    "{{ anyenv.install_dir | replace('~', '$HOME') }}/envs/rbenv/bin/rbenv" rehash
  when: anyenv_gem_installed is changed
